// Code generated by sails-client-gen. DO NOT EDIT.
#[allow(unused_imports)]
use sails_rs::collections::BTreeMap;
#[allow(unused_imports)]
use sails_rs::{
    String,
    calls::{Activation, Call, Query, Remoting, RemotingAction},
    prelude::*,
};
pub struct TemplateFactory<R> {
    #[allow(dead_code)]
    remoting: R,
}
impl<R> TemplateFactory<R> {
    #[allow(unused)]
    pub fn new(remoting: R) -> Self {
        Self { remoting }
    }
}
impl<R: Remoting + Clone> traits::TemplateFactory for TemplateFactory<R> {
    type Args = R::Args;
    fn new(&self, admin: ActorId) -> impl Activation<Args = R::Args> {
        RemotingAction::<_, template_factory::io::New>::new(self.remoting.clone(), admin)
    }
}

pub mod template_factory {
    use super::*;
    pub mod io {
        use super::*;
        use sails_rs::calls::ActionIo;
        pub struct New(());
        impl New {
            #[allow(dead_code)]
            pub fn encode_call(admin: ActorId) -> Vec<u8> {
                <New as ActionIo>::encode_call(&admin)
            }
        }
        impl ActionIo for New {
            const ROUTE: &'static [u8] = &[12, 78, 101, 119];
            type Params = ActorId;
            type Reply = ();
        }
    }
}
pub struct Service<R> {
    remoting: R,
}
impl<R> Service<R> {
    pub fn new(remoting: R) -> Self {
        Self { remoting }
    }
}
impl<R: Remoting + Clone> traits::Service for Service<R> {
    type Args = R::Args;
    /// Step 2: new admin accepts. Caller must be the pending admin.
    fn accept_admin(&mut self) -> impl Call<Output = (), Args = R::Args> {
        RemotingAction::<_, service::io::AcceptAdmin>::new(self.remoting.clone(), ())
    }
    /// Admin cancels a disputed result, clearing all submissions and resetting the
    /// match to Pending so feeders can submit fresh results.
    /// Cannot cancel an already-finalized result (Fix #1).
    fn cancel_result(&mut self, match_id: u64) -> impl Call<Output = (), Args = R::Args> {
        RemotingAction::<_, service::io::CancelResult>::new(self.remoting.clone(), match_id)
    }
    /// Admin force-finalizes a result, bypassing the consensus requirement.
    /// Creates the oracle entry if it does not exist yet.
    fn force_finalize_result(
        &mut self,
        match_id: u64,
        home: u8,
        away: u8,
        penalty_winner: Option<PenaltyWinner>,
    ) -> impl Call<Output = (), Args = R::Args> {
        RemotingAction::<_, service::io::ForceFinalizeResult>::new(
            self.remoting.clone(),
            (match_id, home, away, penalty_winner),
        )
    }
    /// Step 1: propose a new admin. Cannot be the zero address (Fix #3).
    fn propose_admin(&mut self, new_admin: ActorId) -> impl Call<Output = (), Args = R::Args> {
        RemotingAction::<_, service::io::ProposeAdmin>::new(self.remoting.clone(), new_admin)
    }
    /// Admin pre-registers a match_id before feeders can submit results.
    /// Prevents feeders from creating phantom oracle entries for unknown matches.
    fn register_match(&mut self, match_id: u64) -> impl Call<Output = (), Args = R::Args> {
        RemotingAction::<_, service::io::RegisterMatch>::new(self.remoting.clone(), match_id)
    }
    /// Register the BolaoCore program address (informational — used by off-chain tooling).
    fn set_bolao_program(&mut self, program_id: ActorId) -> impl Call<Output = (), Args = R::Args> {
        RemotingAction::<_, service::io::SetBolaoProgram>::new(self.remoting.clone(), program_id)
    }
    /// Update the number of agreeing feeders needed to auto-finalize a result.
    /// Must be >= 1 and <= MAX_FEEDERS; values above MAX_FEEDERS make organic
    /// consensus unreachable.
    fn set_consensus_threshold(&mut self, threshold: u8) -> impl Call<Output = (), Args = R::Args> {
        RemotingAction::<_, service::io::SetConsensusThreshold>::new(
            self.remoting.clone(),
            threshold,
        )
    }
    /// Authorize or revoke a data feeder.
    /// Revoking a feeder excludes their past submissions from future consensus checks.
    fn set_feeder_authorized(
        &mut self,
        feeder: ActorId,
        authorized: bool,
    ) -> impl Call<Output = (), Args = R::Args> {
        RemotingAction::<_, service::io::SetFeederAuthorized>::new(
            self.remoting.clone(),
            (feeder, authorized),
        )
    }
    /// Authorized feeder submits a match result.
    ///
    /// - The match must be pre-registered by admin (Fix #8 — no phantom entries).
    /// - One submission per feeder per match.
    /// - Consensus only counts votes from currently authorized feeders (Fix #4).
    /// - Exactly ONE event is emitted, after the state transition is complete.
    /// - The entry borrow is released in an explicit inner scope before the
    /// consensus re-read, preventing NLL ambiguity (Fix #6).
    fn submit_result(
        &mut self,
        match_id: u64,
        home: u8,
        away: u8,
        penalty_winner: Option<PenaltyWinner>,
    ) -> impl Call<Output = (), Args = R::Args> {
        RemotingAction::<_, service::io::SubmitResult>::new(
            self.remoting.clone(),
            (match_id, home, away, penalty_winner),
        )
    }
    /// Returns a flat view of all oracle entries.
    fn query_all_results(&self) -> impl Query<Output = Vec<IoMatchResult>, Args = R::Args> {
        RemotingAction::<_, service::io::QueryAllResults>::new(self.remoting.clone(), ())
    }
    /// Returns the matches on which a specific feeder has submitted a result.
    fn query_feeder_submissions(
        &self,
        feeder: ActorId,
    ) -> impl Query<Output = Vec<(u64, Score, Option<PenaltyWinner>)>, Args = R::Args> {
        RemotingAction::<_, service::io::QueryFeederSubmissions>::new(self.remoting.clone(), feeder)
    }
    /// Returns the finalized result for a given match, or None if not yet finalized.
    fn query_match_result(
        &self,
        match_id: u64,
    ) -> impl Query<Output = Option<FinalResult>, Args = R::Args> {
        RemotingAction::<_, service::io::QueryMatchResult>::new(self.remoting.clone(), match_id)
    }
    /// Returns all match_ids that are still in Pending status.
    fn query_pending_matches(&self) -> impl Query<Output = Vec<u64>, Args = R::Args> {
        RemotingAction::<_, service::io::QueryPendingMatches>::new(self.remoting.clone(), ())
    }
    /// Full program state — admin, feeders, threshold, all match records.
    fn query_state(&self) -> impl Query<Output = IoOracleState, Args = R::Args> {
        RemotingAction::<_, service::io::QueryState>::new(self.remoting.clone(), ())
    }
}

pub mod service {
    use super::*;

    pub mod io {
        use super::*;
        use sails_rs::calls::ActionIo;
        pub struct AcceptAdmin(());
        impl AcceptAdmin {
            #[allow(dead_code)]
            pub fn encode_call() -> Vec<u8> {
                <AcceptAdmin as ActionIo>::encode_call(&())
            }
        }
        impl ActionIo for AcceptAdmin {
            const ROUTE: &'static [u8] = &[
                28, 83, 101, 114, 118, 105, 99, 101, 44, 65, 99, 99, 101, 112, 116, 65, 100, 109,
                105, 110,
            ];
            type Params = ();
            type Reply = ();
        }
        pub struct CancelResult(());
        impl CancelResult {
            #[allow(dead_code)]
            pub fn encode_call(match_id: u64) -> Vec<u8> {
                <CancelResult as ActionIo>::encode_call(&match_id)
            }
        }
        impl ActionIo for CancelResult {
            const ROUTE: &'static [u8] = &[
                28, 83, 101, 114, 118, 105, 99, 101, 48, 67, 97, 110, 99, 101, 108, 82, 101, 115,
                117, 108, 116,
            ];
            type Params = u64;
            type Reply = ();
        }
        pub struct ForceFinalizeResult(());
        impl ForceFinalizeResult {
            #[allow(dead_code)]
            pub fn encode_call(
                match_id: u64,
                home: u8,
                away: u8,
                penalty_winner: Option<super::PenaltyWinner>,
            ) -> Vec<u8> {
                <ForceFinalizeResult as ActionIo>::encode_call(&(
                    match_id,
                    home,
                    away,
                    penalty_winner,
                ))
            }
        }
        impl ActionIo for ForceFinalizeResult {
            const ROUTE: &'static [u8] = &[
                28, 83, 101, 114, 118, 105, 99, 101, 76, 70, 111, 114, 99, 101, 70, 105, 110, 97,
                108, 105, 122, 101, 82, 101, 115, 117, 108, 116,
            ];
            type Params = (u64, u8, u8, Option<super::PenaltyWinner>);
            type Reply = ();
        }
        pub struct ProposeAdmin(());
        impl ProposeAdmin {
            #[allow(dead_code)]
            pub fn encode_call(new_admin: ActorId) -> Vec<u8> {
                <ProposeAdmin as ActionIo>::encode_call(&new_admin)
            }
        }
        impl ActionIo for ProposeAdmin {
            const ROUTE: &'static [u8] = &[
                28, 83, 101, 114, 118, 105, 99, 101, 48, 80, 114, 111, 112, 111, 115, 101, 65, 100,
                109, 105, 110,
            ];
            type Params = ActorId;
            type Reply = ();
        }
        pub struct RegisterMatch(());
        impl RegisterMatch {
            #[allow(dead_code)]
            pub fn encode_call(match_id: u64) -> Vec<u8> {
                <RegisterMatch as ActionIo>::encode_call(&match_id)
            }
        }
        impl ActionIo for RegisterMatch {
            const ROUTE: &'static [u8] = &[
                28, 83, 101, 114, 118, 105, 99, 101, 52, 82, 101, 103, 105, 115, 116, 101, 114, 77,
                97, 116, 99, 104,
            ];
            type Params = u64;
            type Reply = ();
        }
        pub struct SetBolaoProgram(());
        impl SetBolaoProgram {
            #[allow(dead_code)]
            pub fn encode_call(program_id: ActorId) -> Vec<u8> {
                <SetBolaoProgram as ActionIo>::encode_call(&program_id)
            }
        }
        impl ActionIo for SetBolaoProgram {
            const ROUTE: &'static [u8] = &[
                28, 83, 101, 114, 118, 105, 99, 101, 60, 83, 101, 116, 66, 111, 108, 97, 111, 80,
                114, 111, 103, 114, 97, 109,
            ];
            type Params = ActorId;
            type Reply = ();
        }
        pub struct SetConsensusThreshold(());
        impl SetConsensusThreshold {
            #[allow(dead_code)]
            pub fn encode_call(threshold: u8) -> Vec<u8> {
                <SetConsensusThreshold as ActionIo>::encode_call(&threshold)
            }
        }
        impl ActionIo for SetConsensusThreshold {
            const ROUTE: &'static [u8] = &[
                28, 83, 101, 114, 118, 105, 99, 101, 84, 83, 101, 116, 67, 111, 110, 115, 101, 110,
                115, 117, 115, 84, 104, 114, 101, 115, 104, 111, 108, 100,
            ];
            type Params = u8;
            type Reply = ();
        }
        pub struct SetFeederAuthorized(());
        impl SetFeederAuthorized {
            #[allow(dead_code)]
            pub fn encode_call(feeder: ActorId, authorized: bool) -> Vec<u8> {
                <SetFeederAuthorized as ActionIo>::encode_call(&(feeder, authorized))
            }
        }
        impl ActionIo for SetFeederAuthorized {
            const ROUTE: &'static [u8] = &[
                28, 83, 101, 114, 118, 105, 99, 101, 76, 83, 101, 116, 70, 101, 101, 100, 101, 114,
                65, 117, 116, 104, 111, 114, 105, 122, 101, 100,
            ];
            type Params = (ActorId, bool);
            type Reply = ();
        }
        pub struct SubmitResult(());
        impl SubmitResult {
            #[allow(dead_code)]
            pub fn encode_call(
                match_id: u64,
                home: u8,
                away: u8,
                penalty_winner: Option<super::PenaltyWinner>,
            ) -> Vec<u8> {
                <SubmitResult as ActionIo>::encode_call(&(match_id, home, away, penalty_winner))
            }
        }
        impl ActionIo for SubmitResult {
            const ROUTE: &'static [u8] = &[
                28, 83, 101, 114, 118, 105, 99, 101, 48, 83, 117, 98, 109, 105, 116, 82, 101, 115,
                117, 108, 116,
            ];
            type Params = (u64, u8, u8, Option<super::PenaltyWinner>);
            type Reply = ();
        }
        pub struct QueryAllResults(());
        impl QueryAllResults {
            #[allow(dead_code)]
            pub fn encode_call() -> Vec<u8> {
                <QueryAllResults as ActionIo>::encode_call(&())
            }
        }
        impl ActionIo for QueryAllResults {
            const ROUTE: &'static [u8] = &[
                28, 83, 101, 114, 118, 105, 99, 101, 60, 81, 117, 101, 114, 121, 65, 108, 108, 82,
                101, 115, 117, 108, 116, 115,
            ];
            type Params = ();
            type Reply = Vec<super::IoMatchResult>;
        }
        pub struct QueryFeederSubmissions(());
        impl QueryFeederSubmissions {
            #[allow(dead_code)]
            pub fn encode_call(feeder: ActorId) -> Vec<u8> {
                <QueryFeederSubmissions as ActionIo>::encode_call(&feeder)
            }
        }
        impl ActionIo for QueryFeederSubmissions {
            const ROUTE: &'static [u8] = &[
                28, 83, 101, 114, 118, 105, 99, 101, 88, 81, 117, 101, 114, 121, 70, 101, 101, 100,
                101, 114, 83, 117, 98, 109, 105, 115, 115, 105, 111, 110, 115,
            ];
            type Params = ActorId;
            type Reply = Vec<(u64, super::Score, Option<super::PenaltyWinner>)>;
        }
        pub struct QueryMatchResult(());
        impl QueryMatchResult {
            #[allow(dead_code)]
            pub fn encode_call(match_id: u64) -> Vec<u8> {
                <QueryMatchResult as ActionIo>::encode_call(&match_id)
            }
        }
        impl ActionIo for QueryMatchResult {
            const ROUTE: &'static [u8] = &[
                28, 83, 101, 114, 118, 105, 99, 101, 64, 81, 117, 101, 114, 121, 77, 97, 116, 99,
                104, 82, 101, 115, 117, 108, 116,
            ];
            type Params = u64;
            type Reply = Option<super::FinalResult>;
        }
        pub struct QueryPendingMatches(());
        impl QueryPendingMatches {
            #[allow(dead_code)]
            pub fn encode_call() -> Vec<u8> {
                <QueryPendingMatches as ActionIo>::encode_call(&())
            }
        }
        impl ActionIo for QueryPendingMatches {
            const ROUTE: &'static [u8] = &[
                28, 83, 101, 114, 118, 105, 99, 101, 76, 81, 117, 101, 114, 121, 80, 101, 110, 100,
                105, 110, 103, 77, 97, 116, 99, 104, 101, 115,
            ];
            type Params = ();
            type Reply = Vec<u64>;
        }
        pub struct QueryState(());
        impl QueryState {
            #[allow(dead_code)]
            pub fn encode_call() -> Vec<u8> {
                <QueryState as ActionIo>::encode_call(&())
            }
        }
        impl ActionIo for QueryState {
            const ROUTE: &'static [u8] = &[
                28, 83, 101, 114, 118, 105, 99, 101, 40, 81, 117, 101, 114, 121, 83, 116, 97, 116,
                101,
            ];
            type Params = ();
            type Reply = super::IoOracleState;
        }
    }

    #[allow(dead_code)]
    #[cfg(not(target_arch = "wasm32"))]
    pub mod events {
        use super::*;
        use sails_rs::events::*;
        #[derive(PartialEq, Debug, Encode, Decode)]
        #[codec(crate = sails_rs::scale_codec)]
        pub enum ServiceEvents {
            /// Admin registered a match_id for feeder submissions: (match_id).
            MatchRegistered(u64),
            /// A feeder was authorized or revoked: (feeder, authorized).
            FeederSet((ActorId, bool)),
            /// Consensus threshold was updated: (new_threshold).
            ConsensusThresholdSet(u8),
            /// BolaoCore program address was registered.
            BolaoProgram(ActorId),
            /// A feeder submitted a result: (match_id, feeder, score).
            ResultSubmitted((u64, ActorId, Score)),
            /// Consensus reached and result auto-finalized: (match_id, score, penalty_winner).
            ConsensusReached((u64, Score, Option<PenaltyWinner>)),
            /// Admin force-finalized a result: (match_id, score, penalty_winner).
            ResultForced((u64, Score, Option<PenaltyWinner>)),
            /// Admin cancelled a disputed result and reset it to Pending: (match_id).
            ResultCancelled(u64),
            /// 2-step admin transfer — new admin proposed: (old, proposed).
            AdminProposed((ActorId, ActorId)),
            /// New admin accepted ownership: (old, new).
            AdminChanged((ActorId, ActorId)),
        }
        impl EventIo for ServiceEvents {
            const ROUTE: &'static [u8] = &[28, 83, 101, 114, 118, 105, 99, 101];
            const EVENT_NAMES: &'static [&'static [u8]] = &[
                &[
                    60, 77, 97, 116, 99, 104, 82, 101, 103, 105, 115, 116, 101, 114, 101, 100,
                ],
                &[36, 70, 101, 101, 100, 101, 114, 83, 101, 116],
                &[
                    84, 67, 111, 110, 115, 101, 110, 115, 117, 115, 84, 104, 114, 101, 115, 104,
                    111, 108, 100, 83, 101, 116,
                ],
                &[48, 66, 111, 108, 97, 111, 80, 114, 111, 103, 114, 97, 109],
                &[
                    60, 82, 101, 115, 117, 108, 116, 83, 117, 98, 109, 105, 116, 116, 101, 100,
                ],
                &[
                    64, 67, 111, 110, 115, 101, 110, 115, 117, 115, 82, 101, 97, 99, 104, 101, 100,
                ],
                &[48, 82, 101, 115, 117, 108, 116, 70, 111, 114, 99, 101, 100],
                &[
                    60, 82, 101, 115, 117, 108, 116, 67, 97, 110, 99, 101, 108, 108, 101, 100,
                ],
                &[
                    52, 65, 100, 109, 105, 110, 80, 114, 111, 112, 111, 115, 101, 100,
                ],
                &[48, 65, 100, 109, 105, 110, 67, 104, 97, 110, 103, 101, 100],
            ];
            type Event = Self;
        }
        pub fn listener<R: Listener<Vec<u8>>>(remoting: R) -> impl Listener<ServiceEvents> {
            RemotingListener::<_, ServiceEvents>::new(remoting)
        }
    }
}
/// Penalty shootout winner for knockout draws.
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum PenaltyWinner {
    Home,
    Away,
}
/// Flat view of an oracle result — exposed in `IoOracleState`.
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct IoMatchResult {
    pub match_id: u64,
    pub status: OracleResultStatus,
    pub final_result: Option<FinalResult>,
    pub submissions: u32,
}
/// Lifecycle of an oracle match entry.
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum OracleResultStatus {
    /// Submissions received but consensus not yet reached.
    Pending,
    /// Consensus threshold met — result locked.
    Finalized,
}
/// The verified, locked result for a match.
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct FinalResult {
    pub score: Score,
    pub penalty_winner: Option<PenaltyWinner>,
    pub finalized_at: u64,
}
/// Final score of a match.
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct Score {
    pub home: u8,
    pub away: u8,
}
/// Full read-only projection returned by `query_state()`.
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct IoOracleState {
    pub admin: ActorId,
    pub consensus_threshold: u8,
    pub bolao_program_id: Option<ActorId>,
    pub authorized_feeders: Vec<ActorId>,
    pub match_results: Vec<IoMatchResult>,
    pub pending_admin: Option<ActorId>,
}

pub mod traits {
    use super::*;
    #[allow(dead_code)]
    pub trait TemplateFactory {
        type Args;
        #[allow(clippy::new_ret_no_self)]
        #[allow(clippy::wrong_self_convention)]
        fn new(&self, admin: ActorId) -> impl Activation<Args = Self::Args>;
    }

    #[allow(clippy::type_complexity)]
    pub trait Service {
        type Args;
        fn accept_admin(&mut self) -> impl Call<Output = (), Args = Self::Args>;
        fn cancel_result(&mut self, match_id: u64) -> impl Call<Output = (), Args = Self::Args>;
        fn force_finalize_result(
            &mut self,
            match_id: u64,
            home: u8,
            away: u8,
            penalty_winner: Option<PenaltyWinner>,
        ) -> impl Call<Output = (), Args = Self::Args>;
        fn propose_admin(
            &mut self,
            new_admin: ActorId,
        ) -> impl Call<Output = (), Args = Self::Args>;
        fn register_match(&mut self, match_id: u64) -> impl Call<Output = (), Args = Self::Args>;
        fn set_bolao_program(
            &mut self,
            program_id: ActorId,
        ) -> impl Call<Output = (), Args = Self::Args>;
        fn set_consensus_threshold(
            &mut self,
            threshold: u8,
        ) -> impl Call<Output = (), Args = Self::Args>;
        fn set_feeder_authorized(
            &mut self,
            feeder: ActorId,
            authorized: bool,
        ) -> impl Call<Output = (), Args = Self::Args>;
        fn submit_result(
            &mut self,
            match_id: u64,
            home: u8,
            away: u8,
            penalty_winner: Option<PenaltyWinner>,
        ) -> impl Call<Output = (), Args = Self::Args>;
        fn query_all_results(&self) -> impl Query<Output = Vec<IoMatchResult>, Args = Self::Args>;
        fn query_feeder_submissions(
            &self,
            feeder: ActorId,
        ) -> impl Query<Output = Vec<(u64, Score, Option<PenaltyWinner>)>, Args = Self::Args>;
        fn query_match_result(
            &self,
            match_id: u64,
        ) -> impl Query<Output = Option<FinalResult>, Args = Self::Args>;
        fn query_pending_matches(&self) -> impl Query<Output = Vec<u64>, Args = Self::Args>;
        fn query_state(&self) -> impl Query<Output = IoOracleState, Args = Self::Args>;
    }
}
