// Code generated by sails-client-gen. DO NOT EDIT.
#[allow(unused_imports)]
use sails_rs::collections::BTreeMap;
#[allow(unused_imports)]
use sails_rs::{
    String,
    calls::{Activation, Call, Query, Remoting, RemotingAction},
    prelude::*,
};
pub struct TemplateFactory<R> {
    #[allow(dead_code)]
    remoting: R,
}
impl<R> TemplateFactory<R> {
    #[allow(unused)]
    pub fn new(remoting: R) -> Self {
        Self { remoting }
    }
}
impl<R: Remoting + Clone> traits::TemplateFactory for TemplateFactory<R> {
    type Args = R::Args;
    fn new(&self, admin: ActorId) -> impl Activation<Args = R::Args> {
        RemotingAction::<_, template_factory::io::New>::new(self.remoting.clone(), admin)
    }
}

pub mod template_factory {
    use super::*;
    pub mod io {
        use super::*;
        use sails_rs::calls::ActionIo;
        pub struct New(());
        impl New {
            #[allow(dead_code)]
            pub fn encode_call(admin: ActorId) -> Vec<u8> {
                <New as ActionIo>::encode_call(&admin)
            }
        }
        impl ActionIo for New {
            const ROUTE: &'static [u8] = &[12, 78, 101, 119];
            type Params = ActorId;
            type Reply = ();
        }
    }
}
pub struct Service<R> {
    remoting: R,
}
impl<R> Service<R> {
    pub fn new(remoting: R) -> Self {
        Self { remoting }
    }
}
impl<R: Remoting + Clone> traits::Service for Service<R> {
    type Args = R::Args;
    fn change_admin(
        &mut self,
        new_admin: ActorId,
    ) -> impl Call<Output = SmartCupEvent, Args = R::Args> {
        RemotingAction::<_, service::io::ChangeAdmin>::new(self.remoting.clone(), new_admin)
    }
    fn claim_final_prize(&mut self) -> impl Call<Output = SmartCupEvent, Args = R::Args> {
        RemotingAction::<_, service::io::ClaimFinalPrize>::new(self.remoting.clone(), ())
    }
    fn claim_match_reward(
        &mut self,
        match_id: u64,
    ) -> impl Call<Output = SmartCupEvent, Args = R::Args> {
        RemotingAction::<_, service::io::ClaimMatchReward>::new(self.remoting.clone(), match_id)
    }
    fn finalize_final_prize_pool(&mut self) -> impl Call<Output = SmartCupEvent, Args = R::Args> {
        RemotingAction::<_, service::io::FinalizeFinalPrizePool>::new(self.remoting.clone(), ())
    }
    fn finalize_podium(
        &mut self,
        champion: String,
        runner_up: String,
        third_place: String,
    ) -> impl Call<Output = Vec<SmartCupEvent>, Args = R::Args> {
        RemotingAction::<_, service::io::FinalizePodium>::new(
            self.remoting.clone(),
            (champion, runner_up, third_place),
        )
    }
    fn finalize_result(
        &mut self,
        match_id: u64,
    ) -> impl Call<Output = SmartCupEvent, Args = R::Args> {
        RemotingAction::<_, service::io::FinalizeResult>::new(self.remoting.clone(), match_id)
    }
    fn place_bet(
        &mut self,
        match_id: u64,
        predicted_score: Score,
        predicted_penalty_winner: Option<PenaltyWinner>,
    ) -> impl Call<Output = SmartCupEvent, Args = R::Args> {
        RemotingAction::<_, service::io::PlaceBet>::new(
            self.remoting.clone(),
            (match_id, predicted_score, predicted_penalty_winner),
        )
    }
    fn prepare_match_settlement(
        &mut self,
        match_id: u64,
    ) -> impl Call<Output = SmartCupEvent, Args = R::Args> {
        RemotingAction::<_, service::io::PrepareMatchSettlement>::new(
            self.remoting.clone(),
            match_id,
        )
    }
    fn propose_result(
        &mut self,
        match_id: u64,
        final_score: Score,
        penalty_winner: Option<PenaltyWinner>,
    ) -> impl Call<Output = SmartCupEvent, Args = R::Args> {
        RemotingAction::<_, service::io::ProposeResult>::new(
            self.remoting.clone(),
            (match_id, final_score, penalty_winner),
        )
    }
    fn register_match(
        &mut self,
        phase: String,
        home: String,
        away: String,
        kick_off: u64,
    ) -> impl Call<Output = SmartCupEvent, Args = R::Args> {
        RemotingAction::<_, service::io::RegisterMatch>::new(
            self.remoting.clone(),
            (phase, home, away, kick_off),
        )
    }
    fn register_phase(
        &mut self,
        phase_name: String,
        start_time: u64,
        end_time: u64,
        points_weight: u32,
    ) -> impl Call<Output = SmartCupEvent, Args = R::Args> {
        RemotingAction::<_, service::io::RegisterPhase>::new(
            self.remoting.clone(),
            (phase_name, start_time, end_time, points_weight),
        )
    }
    fn set_oracle_authorized(
        &mut self,
        oracle: ActorId,
        authorized: bool,
    ) -> impl Call<Output = SmartCupEvent, Args = R::Args> {
        RemotingAction::<_, service::io::SetOracleAuthorized>::new(
            self.remoting.clone(),
            (oracle, authorized),
        )
    }
    fn submit_podium_pick(
        &mut self,
        champion: String,
        runner_up: String,
        third_place: String,
    ) -> impl Call<Output = SmartCupEvent, Args = R::Args> {
        RemotingAction::<_, service::io::SubmitPodiumPick>::new(
            self.remoting.clone(),
            (champion, runner_up, third_place),
        )
    }
    fn sweep_match_dust_to_final_prize(
        &mut self,
        match_id: u64,
    ) -> impl Call<Output = SmartCupEvent, Args = R::Args> {
        RemotingAction::<_, service::io::SweepMatchDustToFinalPrize>::new(
            self.remoting.clone(),
            match_id,
        )
    }
    fn withdraw_final_prize_rounding_dust(
        &mut self,
    ) -> impl Call<Output = SmartCupEvent, Args = R::Args> {
        RemotingAction::<_, service::io::WithdrawFinalPrizeRoundingDust>::new(
            self.remoting.clone(),
            (),
        )
    }
    fn withdraw_protocol_fees(&mut self) -> impl Call<Output = SmartCupEvent, Args = R::Args> {
        RemotingAction::<_, service::io::WithdrawProtocolFees>::new(self.remoting.clone(), ())
    }
    fn query_bets_by_user(
        &self,
        user: ActorId,
    ) -> impl Query<Output = Vec<UserBetView>, Args = R::Args> {
        RemotingAction::<_, service::io::QueryBetsByUser>::new(self.remoting.clone(), user)
    }
    fn query_final_prize_claim_status(
        &self,
        wallet: ActorId,
    ) -> impl Query<Output = FinalPrizeClaimStatus, Args = R::Args> {
        RemotingAction::<_, service::io::QueryFinalPrizeClaimStatus>::new(
            self.remoting.clone(),
            wallet,
        )
    }
    fn query_match(&self, match_id: u64) -> impl Query<Output = Option<Match>, Args = R::Args> {
        RemotingAction::<_, service::io::QueryMatch>::new(self.remoting.clone(), match_id)
    }
    fn query_matches_by_phase(
        &self,
        phase: String,
    ) -> impl Query<Output = Vec<Match>, Args = R::Args> {
        RemotingAction::<_, service::io::QueryMatchesByPhase>::new(self.remoting.clone(), phase)
    }
    fn query_state(&self) -> impl Query<Output = IoSmartCupState, Args = R::Args> {
        RemotingAction::<_, service::io::QueryState>::new(self.remoting.clone(), ())
    }
    fn query_user_points(&self, user: ActorId) -> impl Query<Output = u32, Args = R::Args> {
        RemotingAction::<_, service::io::QueryUserPoints>::new(self.remoting.clone(), user)
    }
    fn query_wallet_claim_status(
        &self,
        wallet: ActorId,
    ) -> impl Query<Output = WalletClaimStatus, Args = R::Args> {
        RemotingAction::<_, service::io::QueryWalletClaimStatus>::new(self.remoting.clone(), wallet)
    }
}

pub mod service {
    use super::*;

    pub mod io {
        use super::*;
        use sails_rs::calls::ActionIo;
        pub struct ChangeAdmin(());
        impl ChangeAdmin {
            #[allow(dead_code)]
            pub fn encode_call(new_admin: ActorId) -> Vec<u8> {
                <ChangeAdmin as ActionIo>::encode_call(&new_admin)
            }
        }
        impl ActionIo for ChangeAdmin {
            const ROUTE: &'static [u8] = &[
                28, 83, 101, 114, 118, 105, 99, 101, 44, 67, 104, 97, 110, 103, 101, 65, 100, 109,
                105, 110,
            ];
            type Params = ActorId;
            type Reply = super::SmartCupEvent;
        }
        pub struct ClaimFinalPrize(());
        impl ClaimFinalPrize {
            #[allow(dead_code)]
            pub fn encode_call() -> Vec<u8> {
                <ClaimFinalPrize as ActionIo>::encode_call(&())
            }
        }
        impl ActionIo for ClaimFinalPrize {
            const ROUTE: &'static [u8] = &[
                28, 83, 101, 114, 118, 105, 99, 101, 60, 67, 108, 97, 105, 109, 70, 105, 110, 97,
                108, 80, 114, 105, 122, 101,
            ];
            type Params = ();
            type Reply = super::SmartCupEvent;
        }
        pub struct ClaimMatchReward(());
        impl ClaimMatchReward {
            #[allow(dead_code)]
            pub fn encode_call(match_id: u64) -> Vec<u8> {
                <ClaimMatchReward as ActionIo>::encode_call(&match_id)
            }
        }
        impl ActionIo for ClaimMatchReward {
            const ROUTE: &'static [u8] = &[
                28, 83, 101, 114, 118, 105, 99, 101, 64, 67, 108, 97, 105, 109, 77, 97, 116, 99,
                104, 82, 101, 119, 97, 114, 100,
            ];
            type Params = u64;
            type Reply = super::SmartCupEvent;
        }
        pub struct FinalizeFinalPrizePool(());
        impl FinalizeFinalPrizePool {
            #[allow(dead_code)]
            pub fn encode_call() -> Vec<u8> {
                <FinalizeFinalPrizePool as ActionIo>::encode_call(&())
            }
        }
        impl ActionIo for FinalizeFinalPrizePool {
            const ROUTE: &'static [u8] = &[
                28, 83, 101, 114, 118, 105, 99, 101, 88, 70, 105, 110, 97, 108, 105, 122, 101, 70,
                105, 110, 97, 108, 80, 114, 105, 122, 101, 80, 111, 111, 108,
            ];
            type Params = ();
            type Reply = super::SmartCupEvent;
        }
        pub struct FinalizePodium(());
        impl FinalizePodium {
            #[allow(dead_code)]
            pub fn encode_call(
                champion: String,
                runner_up: String,
                third_place: String,
            ) -> Vec<u8> {
                <FinalizePodium as ActionIo>::encode_call(&(champion, runner_up, third_place))
            }
        }
        impl ActionIo for FinalizePodium {
            const ROUTE: &'static [u8] = &[
                28, 83, 101, 114, 118, 105, 99, 101, 56, 70, 105, 110, 97, 108, 105, 122, 101, 80,
                111, 100, 105, 117, 109,
            ];
            type Params = (String, String, String);
            type Reply = Vec<super::SmartCupEvent>;
        }
        pub struct FinalizeResult(());
        impl FinalizeResult {
            #[allow(dead_code)]
            pub fn encode_call(match_id: u64) -> Vec<u8> {
                <FinalizeResult as ActionIo>::encode_call(&match_id)
            }
        }
        impl ActionIo for FinalizeResult {
            const ROUTE: &'static [u8] = &[
                28, 83, 101, 114, 118, 105, 99, 101, 56, 70, 105, 110, 97, 108, 105, 122, 101, 82,
                101, 115, 117, 108, 116,
            ];
            type Params = u64;
            type Reply = super::SmartCupEvent;
        }
        pub struct PlaceBet(());
        impl PlaceBet {
            #[allow(dead_code)]
            pub fn encode_call(
                match_id: u64,
                predicted_score: super::Score,
                predicted_penalty_winner: Option<super::PenaltyWinner>,
            ) -> Vec<u8> {
                <PlaceBet as ActionIo>::encode_call(&(
                    match_id,
                    predicted_score,
                    predicted_penalty_winner,
                ))
            }
        }
        impl ActionIo for PlaceBet {
            const ROUTE: &'static [u8] = &[
                28, 83, 101, 114, 118, 105, 99, 101, 32, 80, 108, 97, 99, 101, 66, 101, 116,
            ];
            type Params = (u64, super::Score, Option<super::PenaltyWinner>);
            type Reply = super::SmartCupEvent;
        }
        pub struct PrepareMatchSettlement(());
        impl PrepareMatchSettlement {
            #[allow(dead_code)]
            pub fn encode_call(match_id: u64) -> Vec<u8> {
                <PrepareMatchSettlement as ActionIo>::encode_call(&match_id)
            }
        }
        impl ActionIo for PrepareMatchSettlement {
            const ROUTE: &'static [u8] = &[
                28, 83, 101, 114, 118, 105, 99, 101, 88, 80, 114, 101, 112, 97, 114, 101, 77, 97,
                116, 99, 104, 83, 101, 116, 116, 108, 101, 109, 101, 110, 116,
            ];
            type Params = u64;
            type Reply = super::SmartCupEvent;
        }
        pub struct ProposeResult(());
        impl ProposeResult {
            #[allow(dead_code)]
            pub fn encode_call(
                match_id: u64,
                final_score: super::Score,
                penalty_winner: Option<super::PenaltyWinner>,
            ) -> Vec<u8> {
                <ProposeResult as ActionIo>::encode_call(&(match_id, final_score, penalty_winner))
            }
        }
        impl ActionIo for ProposeResult {
            const ROUTE: &'static [u8] = &[
                28, 83, 101, 114, 118, 105, 99, 101, 52, 80, 114, 111, 112, 111, 115, 101, 82, 101,
                115, 117, 108, 116,
            ];
            type Params = (u64, super::Score, Option<super::PenaltyWinner>);
            type Reply = super::SmartCupEvent;
        }
        pub struct RegisterMatch(());
        impl RegisterMatch {
            #[allow(dead_code)]
            pub fn encode_call(
                phase: String,
                home: String,
                away: String,
                kick_off: u64,
            ) -> Vec<u8> {
                <RegisterMatch as ActionIo>::encode_call(&(phase, home, away, kick_off))
            }
        }
        impl ActionIo for RegisterMatch {
            const ROUTE: &'static [u8] = &[
                28, 83, 101, 114, 118, 105, 99, 101, 52, 82, 101, 103, 105, 115, 116, 101, 114, 77,
                97, 116, 99, 104,
            ];
            type Params = (String, String, String, u64);
            type Reply = super::SmartCupEvent;
        }
        pub struct RegisterPhase(());
        impl RegisterPhase {
            #[allow(dead_code)]
            pub fn encode_call(
                phase_name: String,
                start_time: u64,
                end_time: u64,
                points_weight: u32,
            ) -> Vec<u8> {
                <RegisterPhase as ActionIo>::encode_call(&(
                    phase_name,
                    start_time,
                    end_time,
                    points_weight,
                ))
            }
        }
        impl ActionIo for RegisterPhase {
            const ROUTE: &'static [u8] = &[
                28, 83, 101, 114, 118, 105, 99, 101, 52, 82, 101, 103, 105, 115, 116, 101, 114, 80,
                104, 97, 115, 101,
            ];
            type Params = (String, u64, u64, u32);
            type Reply = super::SmartCupEvent;
        }
        pub struct SetOracleAuthorized(());
        impl SetOracleAuthorized {
            #[allow(dead_code)]
            pub fn encode_call(oracle: ActorId, authorized: bool) -> Vec<u8> {
                <SetOracleAuthorized as ActionIo>::encode_call(&(oracle, authorized))
            }
        }
        impl ActionIo for SetOracleAuthorized {
            const ROUTE: &'static [u8] = &[
                28, 83, 101, 114, 118, 105, 99, 101, 76, 83, 101, 116, 79, 114, 97, 99, 108, 101,
                65, 117, 116, 104, 111, 114, 105, 122, 101, 100,
            ];
            type Params = (ActorId, bool);
            type Reply = super::SmartCupEvent;
        }
        pub struct SubmitPodiumPick(());
        impl SubmitPodiumPick {
            #[allow(dead_code)]
            pub fn encode_call(
                champion: String,
                runner_up: String,
                third_place: String,
            ) -> Vec<u8> {
                <SubmitPodiumPick as ActionIo>::encode_call(&(champion, runner_up, third_place))
            }
        }
        impl ActionIo for SubmitPodiumPick {
            const ROUTE: &'static [u8] = &[
                28, 83, 101, 114, 118, 105, 99, 101, 64, 83, 117, 98, 109, 105, 116, 80, 111, 100,
                105, 117, 109, 80, 105, 99, 107,
            ];
            type Params = (String, String, String);
            type Reply = super::SmartCupEvent;
        }
        pub struct SweepMatchDustToFinalPrize(());
        impl SweepMatchDustToFinalPrize {
            #[allow(dead_code)]
            pub fn encode_call(match_id: u64) -> Vec<u8> {
                <SweepMatchDustToFinalPrize as ActionIo>::encode_call(&match_id)
            }
        }
        impl ActionIo for SweepMatchDustToFinalPrize {
            const ROUTE: &'static [u8] = &[
                28, 83, 101, 114, 118, 105, 99, 101, 104, 83, 119, 101, 101, 112, 77, 97, 116, 99,
                104, 68, 117, 115, 116, 84, 111, 70, 105, 110, 97, 108, 80, 114, 105, 122, 101,
            ];
            type Params = u64;
            type Reply = super::SmartCupEvent;
        }
        pub struct WithdrawFinalPrizeRoundingDust(());
        impl WithdrawFinalPrizeRoundingDust {
            #[allow(dead_code)]
            pub fn encode_call() -> Vec<u8> {
                <WithdrawFinalPrizeRoundingDust as ActionIo>::encode_call(&())
            }
        }
        impl ActionIo for WithdrawFinalPrizeRoundingDust {
            const ROUTE: &'static [u8] = &[
                28, 83, 101, 114, 118, 105, 99, 101, 120, 87, 105, 116, 104, 100, 114, 97, 119, 70,
                105, 110, 97, 108, 80, 114, 105, 122, 101, 82, 111, 117, 110, 100, 105, 110, 103,
                68, 117, 115, 116,
            ];
            type Params = ();
            type Reply = super::SmartCupEvent;
        }
        pub struct WithdrawProtocolFees(());
        impl WithdrawProtocolFees {
            #[allow(dead_code)]
            pub fn encode_call() -> Vec<u8> {
                <WithdrawProtocolFees as ActionIo>::encode_call(&())
            }
        }
        impl ActionIo for WithdrawProtocolFees {
            const ROUTE: &'static [u8] = &[
                28, 83, 101, 114, 118, 105, 99, 101, 80, 87, 105, 116, 104, 100, 114, 97, 119, 80,
                114, 111, 116, 111, 99, 111, 108, 70, 101, 101, 115,
            ];
            type Params = ();
            type Reply = super::SmartCupEvent;
        }
        pub struct QueryBetsByUser(());
        impl QueryBetsByUser {
            #[allow(dead_code)]
            pub fn encode_call(user: ActorId) -> Vec<u8> {
                <QueryBetsByUser as ActionIo>::encode_call(&user)
            }
        }
        impl ActionIo for QueryBetsByUser {
            const ROUTE: &'static [u8] = &[
                28, 83, 101, 114, 118, 105, 99, 101, 60, 81, 117, 101, 114, 121, 66, 101, 116, 115,
                66, 121, 85, 115, 101, 114,
            ];
            type Params = ActorId;
            type Reply = Vec<super::UserBetView>;
        }
        pub struct QueryFinalPrizeClaimStatus(());
        impl QueryFinalPrizeClaimStatus {
            #[allow(dead_code)]
            pub fn encode_call(wallet: ActorId) -> Vec<u8> {
                <QueryFinalPrizeClaimStatus as ActionIo>::encode_call(&wallet)
            }
        }
        impl ActionIo for QueryFinalPrizeClaimStatus {
            const ROUTE: &'static [u8] = &[
                28, 83, 101, 114, 118, 105, 99, 101, 104, 81, 117, 101, 114, 121, 70, 105, 110, 97,
                108, 80, 114, 105, 122, 101, 67, 108, 97, 105, 109, 83, 116, 97, 116, 117, 115,
            ];
            type Params = ActorId;
            type Reply = super::FinalPrizeClaimStatus;
        }
        pub struct QueryMatch(());
        impl QueryMatch {
            #[allow(dead_code)]
            pub fn encode_call(match_id: u64) -> Vec<u8> {
                <QueryMatch as ActionIo>::encode_call(&match_id)
            }
        }
        impl ActionIo for QueryMatch {
            const ROUTE: &'static [u8] = &[
                28, 83, 101, 114, 118, 105, 99, 101, 40, 81, 117, 101, 114, 121, 77, 97, 116, 99,
                104,
            ];
            type Params = u64;
            type Reply = Option<super::Match>;
        }
        pub struct QueryMatchesByPhase(());
        impl QueryMatchesByPhase {
            #[allow(dead_code)]
            pub fn encode_call(phase: String) -> Vec<u8> {
                <QueryMatchesByPhase as ActionIo>::encode_call(&phase)
            }
        }
        impl ActionIo for QueryMatchesByPhase {
            const ROUTE: &'static [u8] = &[
                28, 83, 101, 114, 118, 105, 99, 101, 76, 81, 117, 101, 114, 121, 77, 97, 116, 99,
                104, 101, 115, 66, 121, 80, 104, 97, 115, 101,
            ];
            type Params = String;
            type Reply = Vec<super::Match>;
        }
        pub struct QueryState(());
        impl QueryState {
            #[allow(dead_code)]
            pub fn encode_call() -> Vec<u8> {
                <QueryState as ActionIo>::encode_call(&())
            }
        }
        impl ActionIo for QueryState {
            const ROUTE: &'static [u8] = &[
                28, 83, 101, 114, 118, 105, 99, 101, 40, 81, 117, 101, 114, 121, 83, 116, 97, 116,
                101,
            ];
            type Params = ();
            type Reply = super::IoSmartCupState;
        }
        pub struct QueryUserPoints(());
        impl QueryUserPoints {
            #[allow(dead_code)]
            pub fn encode_call(user: ActorId) -> Vec<u8> {
                <QueryUserPoints as ActionIo>::encode_call(&user)
            }
        }
        impl ActionIo for QueryUserPoints {
            const ROUTE: &'static [u8] = &[
                28, 83, 101, 114, 118, 105, 99, 101, 60, 81, 117, 101, 114, 121, 85, 115, 101, 114,
                80, 111, 105, 110, 116, 115,
            ];
            type Params = ActorId;
            type Reply = u32;
        }
        pub struct QueryWalletClaimStatus(());
        impl QueryWalletClaimStatus {
            #[allow(dead_code)]
            pub fn encode_call(wallet: ActorId) -> Vec<u8> {
                <QueryWalletClaimStatus as ActionIo>::encode_call(&wallet)
            }
        }
        impl ActionIo for QueryWalletClaimStatus {
            const ROUTE: &'static [u8] = &[
                28, 83, 101, 114, 118, 105, 99, 101, 88, 81, 117, 101, 114, 121, 87, 97, 108, 108,
                101, 116, 67, 108, 97, 105, 109, 83, 116, 97, 116, 117, 115,
            ];
            type Params = ActorId;
            type Reply = super::WalletClaimStatus;
        }
    }

    #[allow(dead_code)]
    #[cfg(not(target_arch = "wasm32"))]
    pub mod events {
        use super::*;
        use sails_rs::events::*;
        #[derive(PartialEq, Debug, Encode, Decode)]
        #[codec(crate = sails_rs::scale_codec)]
        pub enum ServiceEvents {
            PhaseRegistered(String),
            MatchRegistered((u64, String, String, String, u64)),
            OracleAuthorized((ActorId, bool)),
            BetAccepted((ActorId, u64, Score, Option<PenaltyWinner>, u128)),
            ResultProposed((u64, Score, Option<PenaltyWinner>, ActorId)),
            ResultFinalized((u64, Score, Option<PenaltyWinner>)),
            SettlementPrepared((u64, u128)),
            PointsAwarded((ActorId, u64, u32)),
            MatchRewardClaimed((u64, ActorId, u128)),
            MatchDustSwept((u64, u128)),
            PodiumPickSubmitted((ActorId, String, String, String)),
            PodiumFinalized((String, String, String)),
            PodiumBonusAwarded((ActorId, u32)),
            FinalPrizeSent((u128, ActorId)),
            ProtocolFeesWithdrawn((u128, ActorId)),
            AdminChanged((ActorId, ActorId)),
            FinalPrizePoolFinalized((u128, u128)),
            FinalPrizeClaimed((ActorId, u128)),
            FinalPrizeRoundingDustWithdrawn((u128, ActorId)),
        }
        impl EventIo for ServiceEvents {
            const ROUTE: &'static [u8] = &[28, 83, 101, 114, 118, 105, 99, 101];
            const EVENT_NAMES: &'static [&'static [u8]] = &[
                &[
                    60, 80, 104, 97, 115, 101, 82, 101, 103, 105, 115, 116, 101, 114, 101, 100,
                ],
                &[
                    60, 77, 97, 116, 99, 104, 82, 101, 103, 105, 115, 116, 101, 114, 101, 100,
                ],
                &[
                    64, 79, 114, 97, 99, 108, 101, 65, 117, 116, 104, 111, 114, 105, 122, 101, 100,
                ],
                &[44, 66, 101, 116, 65, 99, 99, 101, 112, 116, 101, 100],
                &[
                    56, 82, 101, 115, 117, 108, 116, 80, 114, 111, 112, 111, 115, 101, 100,
                ],
                &[
                    60, 82, 101, 115, 117, 108, 116, 70, 105, 110, 97, 108, 105, 122, 101, 100,
                ],
                &[
                    72, 83, 101, 116, 116, 108, 101, 109, 101, 110, 116, 80, 114, 101, 112, 97,
                    114, 101, 100,
                ],
                &[
                    52, 80, 111, 105, 110, 116, 115, 65, 119, 97, 114, 100, 101, 100,
                ],
                &[
                    72, 77, 97, 116, 99, 104, 82, 101, 119, 97, 114, 100, 67, 108, 97, 105, 109,
                    101, 100,
                ],
                &[
                    56, 77, 97, 116, 99, 104, 68, 117, 115, 116, 83, 119, 101, 112, 116,
                ],
                &[
                    76, 80, 111, 100, 105, 117, 109, 80, 105, 99, 107, 83, 117, 98, 109, 105, 116,
                    116, 101, 100,
                ],
                &[
                    60, 80, 111, 100, 105, 117, 109, 70, 105, 110, 97, 108, 105, 122, 101, 100,
                ],
                &[
                    72, 80, 111, 100, 105, 117, 109, 66, 111, 110, 117, 115, 65, 119, 97, 114, 100,
                    101, 100,
                ],
                &[
                    56, 70, 105, 110, 97, 108, 80, 114, 105, 122, 101, 83, 101, 110, 116,
                ],
                &[
                    84, 80, 114, 111, 116, 111, 99, 111, 108, 70, 101, 101, 115, 87, 105, 116, 104,
                    100, 114, 97, 119, 110,
                ],
                &[48, 65, 100, 109, 105, 110, 67, 104, 97, 110, 103, 101, 100],
                &[
                    92, 70, 105, 110, 97, 108, 80, 114, 105, 122, 101, 80, 111, 111, 108, 70, 105,
                    110, 97, 108, 105, 122, 101, 100,
                ],
                &[
                    68, 70, 105, 110, 97, 108, 80, 114, 105, 122, 101, 67, 108, 97, 105, 109, 101,
                    100,
                ],
                &[
                    124, 70, 105, 110, 97, 108, 80, 114, 105, 122, 101, 82, 111, 117, 110, 100,
                    105, 110, 103, 68, 117, 115, 116, 87, 105, 116, 104, 100, 114, 97, 119, 110,
                ],
            ];
            type Event = Self;
        }
        pub fn listener<R: Listener<Vec<u8>>>(remoting: R) -> impl Listener<ServiceEvents> {
            RemotingListener::<_, ServiceEvents>::new(remoting)
        }
    }
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct Score {
    pub home: u8,
    pub away: u8,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum PenaltyWinner {
    Home,
    Away,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct UserBetView {
    pub match_id: u64,
    pub score: Score,
    pub penalty_winner: Option<PenaltyWinner>,
    pub stake_in_match_pool: u128,
    pub claimed: bool,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct FinalPrizeClaimStatus {
    pub wallet: ActorId,
    pub final_prize_finalized: bool,
    pub eligible: bool,
    pub amount_claimable: u128,
    pub already_claimed: bool,
    pub points: u32,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct Match {
    pub match_id: u64,
    pub phase: String,
    pub home: String,
    pub away: String,
    pub kick_off: u64,
    pub result: ResultStatus,
    pub match_prize_pool: u128,
    pub has_bets: bool,
    pub participants: Vec<ActorId>,
    pub total_winner_stake: u128,
    pub total_claimed: u128,
    pub settlement_prepared: bool,
    pub dust_swept: bool,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum ResultStatus {
    Unresolved,
    Proposed {
        score: Score,
        penalty_winner: Option<PenaltyWinner>,
        oracle: ActorId,
    },
    Finalized {
        score: Score,
        penalty_winner: Option<PenaltyWinner>,
    },
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct IoSmartCupState {
    pub admin: ActorId,
    pub protocol_fee_accumulated: u128,
    pub final_prize_accumulated: u128,
    pub matches: Vec<Match>,
    pub phases: Vec<PhaseConfig>,
    pub user_points: Vec<(ActorId, u32)>,
    pub podium_finalized: bool,
    pub r32_lock_time: Option<u64>,
    pub final_prize_finalized: bool,
    pub final_prize_claimable_total: u128,
    pub final_prize_rounding_dust: u128,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct PhaseConfig {
    pub name: String,
    pub start_time: u64,
    pub end_time: u64,
    pub points_weight: u32,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct WalletClaimStatus {
    pub wallet: ActorId,
    pub amount_claimable: u128,
    pub already_claimed: bool,
}

pub mod traits {
    use super::*;
    #[allow(dead_code)]
    pub trait TemplateFactory {
        type Args;
        #[allow(clippy::new_ret_no_self)]
        #[allow(clippy::wrong_self_convention)]
        fn new(&self, admin: ActorId) -> impl Activation<Args = Self::Args>;
    }

    #[allow(clippy::type_complexity)]
    pub trait Service {
        type Args;
        fn change_admin(
            &mut self,
            new_admin: ActorId,
        ) -> impl Call<Output = SmartCupEvent, Args = Self::Args>;
        fn claim_final_prize(&mut self) -> impl Call<Output = SmartCupEvent, Args = Self::Args>;
        fn claim_match_reward(
            &mut self,
            match_id: u64,
        ) -> impl Call<Output = SmartCupEvent, Args = Self::Args>;
        fn finalize_final_prize_pool(
            &mut self,
        ) -> impl Call<Output = SmartCupEvent, Args = Self::Args>;
        fn finalize_podium(
            &mut self,
            champion: String,
            runner_up: String,
            third_place: String,
        ) -> impl Call<Output = Vec<SmartCupEvent>, Args = Self::Args>;
        fn finalize_result(
            &mut self,
            match_id: u64,
        ) -> impl Call<Output = SmartCupEvent, Args = Self::Args>;
        fn place_bet(
            &mut self,
            match_id: u64,
            predicted_score: Score,
            predicted_penalty_winner: Option<PenaltyWinner>,
        ) -> impl Call<Output = SmartCupEvent, Args = Self::Args>;
        fn prepare_match_settlement(
            &mut self,
            match_id: u64,
        ) -> impl Call<Output = SmartCupEvent, Args = Self::Args>;
        fn propose_result(
            &mut self,
            match_id: u64,
            final_score: Score,
            penalty_winner: Option<PenaltyWinner>,
        ) -> impl Call<Output = SmartCupEvent, Args = Self::Args>;
        fn register_match(
            &mut self,
            phase: String,
            home: String,
            away: String,
            kick_off: u64,
        ) -> impl Call<Output = SmartCupEvent, Args = Self::Args>;
        fn register_phase(
            &mut self,
            phase_name: String,
            start_time: u64,
            end_time: u64,
            points_weight: u32,
        ) -> impl Call<Output = SmartCupEvent, Args = Self::Args>;
        fn set_oracle_authorized(
            &mut self,
            oracle: ActorId,
            authorized: bool,
        ) -> impl Call<Output = SmartCupEvent, Args = Self::Args>;
        fn submit_podium_pick(
            &mut self,
            champion: String,
            runner_up: String,
            third_place: String,
        ) -> impl Call<Output = SmartCupEvent, Args = Self::Args>;
        fn sweep_match_dust_to_final_prize(
            &mut self,
            match_id: u64,
        ) -> impl Call<Output = SmartCupEvent, Args = Self::Args>;
        fn withdraw_final_prize_rounding_dust(
            &mut self,
        ) -> impl Call<Output = SmartCupEvent, Args = Self::Args>;
        fn withdraw_protocol_fees(
            &mut self,
        ) -> impl Call<Output = SmartCupEvent, Args = Self::Args>;
        fn query_bets_by_user(
            &self,
            user: ActorId,
        ) -> impl Query<Output = Vec<UserBetView>, Args = Self::Args>;
        fn query_final_prize_claim_status(
            &self,
            wallet: ActorId,
        ) -> impl Query<Output = FinalPrizeClaimStatus, Args = Self::Args>;
        fn query_match(
            &self,
            match_id: u64,
        ) -> impl Query<Output = Option<Match>, Args = Self::Args>;
        fn query_matches_by_phase(
            &self,
            phase: String,
        ) -> impl Query<Output = Vec<Match>, Args = Self::Args>;
        fn query_state(&self) -> impl Query<Output = IoSmartCupState, Args = Self::Args>;
        fn query_user_points(&self, user: ActorId) -> impl Query<Output = u32, Args = Self::Args>;
        fn query_wallet_claim_status(
            &self,
            wallet: ActorId,
        ) -> impl Query<Output = WalletClaimStatus, Args = Self::Args>;
    }
}
