// Code generated by sails-client-gen. DO NOT EDIT.
#[allow(unused_imports)]
use sails_rs::{client::*, collections::*, prelude::*};
pub struct OracleProgram;
impl sails_rs::client::Program for OracleProgram {}
pub trait Oracle {
    type Env: sails_rs::client::GearEnv;
    fn service(&self) -> sails_rs::client::Service<service::ServiceImpl, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> Oracle for sails_rs::client::Actor<OracleProgram, E> {
    type Env = E;
    fn service(&self) -> sails_rs::client::Service<service::ServiceImpl, Self::Env> {
        self.service(stringify!(Service))
    }
}
pub trait OracleCtors {
    type Env: sails_rs::client::GearEnv;
    #[allow(clippy::new_ret_no_self)]
    #[allow(clippy::wrong_self_convention)]
    fn new(
        self,
        admin: ActorId,
    ) -> sails_rs::client::PendingCtor<OracleProgram, io::New, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> OracleCtors for sails_rs::client::Deployment<OracleProgram, E> {
    type Env = E;
    fn new(
        self,
        admin: ActorId,
    ) -> sails_rs::client::PendingCtor<OracleProgram, io::New, Self::Env> {
        self.pending_ctor((admin,))
    }
}

pub mod io {
    use super::*;
    sails_rs::io_struct_impl!(New (admin: ActorId) -> ());
}

pub mod service {
    use super::*;
    pub trait Service {
        type Env: sails_rs::client::GearEnv;
        /// Step 2: new admin accepts. Caller must be the pending admin.
        fn accept_admin(&mut self) -> sails_rs::client::PendingCall<io::AcceptAdmin, Self::Env>;
        /// Admin cancels a disputed result, clearing all submissions and resetting the
        /// match to Pending so feeders can submit fresh results.
        /// Cannot cancel an already-finalized result (Fix #1).
        fn cancel_result(
            &mut self,
            match_id: u64,
        ) -> sails_rs::client::PendingCall<io::CancelResult, Self::Env>;
        /// Admin force-finalizes a result, bypassing the consensus requirement.
        /// Creates the oracle entry if it does not exist yet.
        fn force_finalize_result(
            &mut self,
            match_id: u64,
            home: u8,
            away: u8,
            penalty_winner: Option<PenaltyWinner>,
        ) -> sails_rs::client::PendingCall<io::ForceFinalizeResult, Self::Env>;
        /// Step 1: propose a new admin. Cannot be the zero address (Fix #3).
        fn propose_admin(
            &mut self,
            new_admin: ActorId,
        ) -> sails_rs::client::PendingCall<io::ProposeAdmin, Self::Env>;
        /// Admin pre-registers a match_id before feeders can submit results.
        /// Prevents feeders from creating phantom oracle entries for unknown matches.
        fn register_match(
            &mut self,
            match_id: u64,
        ) -> sails_rs::client::PendingCall<io::RegisterMatch, Self::Env>;
        /// Register the BolaoCore program address (informational — used by off-chain tooling).
        fn set_bolao_program(
            &mut self,
            program_id: ActorId,
        ) -> sails_rs::client::PendingCall<io::SetBolaoProgram, Self::Env>;
        /// Update the number of agreeing feeders needed to auto-finalize a result.
        /// Must be >= 1 and <= MAX_FEEDERS; values above MAX_FEEDERS make organic
        /// consensus unreachable.
        fn set_consensus_threshold(
            &mut self,
            threshold: u8,
        ) -> sails_rs::client::PendingCall<io::SetConsensusThreshold, Self::Env>;
        /// Authorize or revoke a data feeder.
        /// Revoking a feeder excludes their past submissions from future consensus checks.
        fn set_feeder_authorized(
            &mut self,
            feeder: ActorId,
            authorized: bool,
        ) -> sails_rs::client::PendingCall<io::SetFeederAuthorized, Self::Env>;
        /// Authorized feeder submits a match result.
        ///
        /// - The match must be pre-registered by admin (Fix #8 — no phantom entries).
        /// - One submission per feeder per match.
        /// - Consensus only counts votes from currently authorized feeders (Fix #4).
        /// - Exactly ONE event is emitted, after the state transition is complete.
        /// - The entry borrow is released in an explicit inner scope before the
        /// consensus re-read, preventing NLL ambiguity (Fix #6).
        fn submit_result(
            &mut self,
            match_id: u64,
            home: u8,
            away: u8,
            penalty_winner: Option<PenaltyWinner>,
        ) -> sails_rs::client::PendingCall<io::SubmitResult, Self::Env>;
        /// Returns a flat view of all oracle entries.
        fn query_all_results(
            &self,
        ) -> sails_rs::client::PendingCall<io::QueryAllResults, Self::Env>;
        /// Returns the matches on which a specific feeder has submitted a result.
        fn query_feeder_submissions(
            &self,
            feeder: ActorId,
        ) -> sails_rs::client::PendingCall<io::QueryFeederSubmissions, Self::Env>;
        /// Returns the finalized result for a given match, or None if not yet finalized.
        fn query_match_result(
            &self,
            match_id: u64,
        ) -> sails_rs::client::PendingCall<io::QueryMatchResult, Self::Env>;
        /// Returns all match_ids that are still in Pending status.
        fn query_pending_matches(
            &self,
        ) -> sails_rs::client::PendingCall<io::QueryPendingMatches, Self::Env>;
        /// Full program state — admin, feeders, threshold, all match records.
        fn query_state(&self) -> sails_rs::client::PendingCall<io::QueryState, Self::Env>;
    }
    pub struct ServiceImpl;
    impl<E: sails_rs::client::GearEnv> Service for sails_rs::client::Service<ServiceImpl, E> {
        type Env = E;
        fn accept_admin(&mut self) -> sails_rs::client::PendingCall<io::AcceptAdmin, Self::Env> {
            self.pending_call(())
        }
        fn cancel_result(
            &mut self,
            match_id: u64,
        ) -> sails_rs::client::PendingCall<io::CancelResult, Self::Env> {
            self.pending_call((match_id,))
        }
        fn force_finalize_result(
            &mut self,
            match_id: u64,
            home: u8,
            away: u8,
            penalty_winner: Option<PenaltyWinner>,
        ) -> sails_rs::client::PendingCall<io::ForceFinalizeResult, Self::Env> {
            self.pending_call((match_id, home, away, penalty_winner))
        }
        fn propose_admin(
            &mut self,
            new_admin: ActorId,
        ) -> sails_rs::client::PendingCall<io::ProposeAdmin, Self::Env> {
            self.pending_call((new_admin,))
        }
        fn register_match(
            &mut self,
            match_id: u64,
        ) -> sails_rs::client::PendingCall<io::RegisterMatch, Self::Env> {
            self.pending_call((match_id,))
        }
        fn set_bolao_program(
            &mut self,
            program_id: ActorId,
        ) -> sails_rs::client::PendingCall<io::SetBolaoProgram, Self::Env> {
            self.pending_call((program_id,))
        }
        fn set_consensus_threshold(
            &mut self,
            threshold: u8,
        ) -> sails_rs::client::PendingCall<io::SetConsensusThreshold, Self::Env> {
            self.pending_call((threshold,))
        }
        fn set_feeder_authorized(
            &mut self,
            feeder: ActorId,
            authorized: bool,
        ) -> sails_rs::client::PendingCall<io::SetFeederAuthorized, Self::Env> {
            self.pending_call((feeder, authorized))
        }
        fn submit_result(
            &mut self,
            match_id: u64,
            home: u8,
            away: u8,
            penalty_winner: Option<PenaltyWinner>,
        ) -> sails_rs::client::PendingCall<io::SubmitResult, Self::Env> {
            self.pending_call((match_id, home, away, penalty_winner))
        }
        fn query_all_results(
            &self,
        ) -> sails_rs::client::PendingCall<io::QueryAllResults, Self::Env> {
            self.pending_call(())
        }
        fn query_feeder_submissions(
            &self,
            feeder: ActorId,
        ) -> sails_rs::client::PendingCall<io::QueryFeederSubmissions, Self::Env> {
            self.pending_call((feeder,))
        }
        fn query_match_result(
            &self,
            match_id: u64,
        ) -> sails_rs::client::PendingCall<io::QueryMatchResult, Self::Env> {
            self.pending_call((match_id,))
        }
        fn query_pending_matches(
            &self,
        ) -> sails_rs::client::PendingCall<io::QueryPendingMatches, Self::Env> {
            self.pending_call(())
        }
        fn query_state(&self) -> sails_rs::client::PendingCall<io::QueryState, Self::Env> {
            self.pending_call(())
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(AcceptAdmin () -> ());
        sails_rs::io_struct_impl!(CancelResult (match_id: u64) -> ());
        sails_rs::io_struct_impl!(ForceFinalizeResult (match_id: u64, home: u8, away: u8, penalty_winner: Option<super::PenaltyWinner>) -> ());
        sails_rs::io_struct_impl!(ProposeAdmin (new_admin: ActorId) -> ());
        sails_rs::io_struct_impl!(RegisterMatch (match_id: u64) -> ());
        sails_rs::io_struct_impl!(SetBolaoProgram (program_id: ActorId) -> ());
        sails_rs::io_struct_impl!(SetConsensusThreshold (threshold: u8) -> ());
        sails_rs::io_struct_impl!(SetFeederAuthorized (feeder: ActorId, authorized: bool) -> ());
        sails_rs::io_struct_impl!(SubmitResult (match_id: u64, home: u8, away: u8, penalty_winner: Option<super::PenaltyWinner>) -> ());
        sails_rs::io_struct_impl!(QueryAllResults () -> Vec<super::IoMatchResult>);
        sails_rs::io_struct_impl!(QueryFeederSubmissions (feeder: ActorId) -> Vec<(u64,super::Score,Option<super::PenaltyWinner>,)>);
        sails_rs::io_struct_impl!(QueryMatchResult (match_id: u64) -> Option<super::FinalResult>);
        sails_rs::io_struct_impl!(QueryPendingMatches () -> Vec<u64>);
        sails_rs::io_struct_impl!(QueryState () -> super::IoOracleState);
    }

    #[cfg(not(target_arch = "wasm32"))]
    pub mod events {
        use super::*;
        #[derive(PartialEq, Debug, Encode, Decode)]
        #[codec(crate = sails_rs::scale_codec)]
        pub enum ServiceEvents {
            /// Admin registered a match_id for feeder submissions: (match_id).
            MatchRegistered(u64),
            /// A feeder was authorized or revoked: (feeder, authorized).
            FeederSet((ActorId, bool)),
            /// Consensus threshold was updated: (new_threshold).
            ConsensusThresholdSet(u8),
            /// BolaoCore program address was registered.
            BolaoProgram(ActorId),
            /// A feeder submitted a result: (match_id, feeder, score).
            ResultSubmitted((u64, ActorId, Score)),
            /// Consensus reached and result auto-finalized: (match_id, score, penalty_winner).
            ConsensusReached((u64, Score, Option<PenaltyWinner>)),
            /// Admin force-finalized a result: (match_id, score, penalty_winner).
            ResultForced((u64, Score, Option<PenaltyWinner>)),
            /// Admin cancelled a disputed result and reset it to Pending: (match_id).
            ResultCancelled(u64),
            /// 2-step admin transfer — new admin proposed: (old, proposed).
            AdminProposed((ActorId, ActorId)),
            /// New admin accepted ownership: (old, new).
            AdminChanged((ActorId, ActorId)),
        }
        impl sails_rs::client::Event for ServiceEvents {
            const EVENT_NAMES: &'static [Route] = &[
                "MatchRegistered",
                "FeederSet",
                "ConsensusThresholdSet",
                "BolaoProgram",
                "ResultSubmitted",
                "ConsensusReached",
                "ResultForced",
                "ResultCancelled",
                "AdminProposed",
                "AdminChanged",
            ];
        }
        impl sails_rs::client::ServiceWithEvents for ServiceImpl {
            type Event = ServiceEvents;
        }
    }
}
/// Penalty shootout winner for knockout draws.
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum PenaltyWinner {
    Home,
    Away,
}
/// Flat view of an oracle result — exposed in `IoOracleState`.
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct IoMatchResult {
    pub match_id: u64,
    pub status: OracleResultStatus,
    pub final_result: Option<FinalResult>,
    pub submissions: u32,
}
/// Lifecycle of an oracle match entry.
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum OracleResultStatus {
    /// Submissions received but consensus not yet reached.
    Pending,
    /// Consensus threshold met — result locked.
    Finalized,
}
/// The verified, locked result for a match.
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct FinalResult {
    pub score: Score,
    pub penalty_winner: Option<PenaltyWinner>,
    pub finalized_at: u64,
}
/// Final score of a match.
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct Score {
    pub home: u8,
    pub away: u8,
}
/// Full read-only projection returned by `query_state()`.
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct IoOracleState {
    pub admin: ActorId,
    pub consensus_threshold: u8,
    pub bolao_program_id: Option<ActorId>,
    pub authorized_feeders: Vec<ActorId>,
    pub match_results: Vec<IoMatchResult>,
    pub pending_admin: Option<ActorId>,
}
