// Code generated by sails-client-gen. DO NOT EDIT.
#[allow(unused_imports)]
use sails_rs::{client::*, collections::*, prelude::*};
pub struct BolaoProgram;
impl sails_rs::client::Program for BolaoProgram {}
pub trait Bolao {
    type Env: sails_rs::client::GearEnv;
    fn service(&self) -> sails_rs::client::Service<service::ServiceImpl, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> Bolao for sails_rs::client::Actor<BolaoProgram, E> {
    type Env = E;
    fn service(&self) -> sails_rs::client::Service<service::ServiceImpl, Self::Env> {
        self.service(stringify!(Service))
    }
}
pub trait BolaoCtors {
    type Env: sails_rs::client::GearEnv;
    #[allow(clippy::new_ret_no_self)]
    #[allow(clippy::wrong_self_convention)]
    fn new(self, admin: ActorId)
    -> sails_rs::client::PendingCtor<BolaoProgram, io::New, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> BolaoCtors for sails_rs::client::Deployment<BolaoProgram, E> {
    type Env = E;
    fn new(
        self,
        admin: ActorId,
    ) -> sails_rs::client::PendingCtor<BolaoProgram, io::New, Self::Env> {
        self.pending_ctor((admin,))
    }
}

pub mod io {
    use super::*;
    sails_rs::io_struct_impl!(New (admin: ActorId) -> ());
}

pub mod service {
    use super::*;
    pub trait Service {
        type Env: sails_rs::client::GearEnv;
        /// Step 2 of 2-step admin transfer: pending admin confirms ownership.
        /// Must be called by the address previously set via change_admin().
        fn accept_admin(&mut self) -> sails_rs::client::PendingCall<io::AcceptAdmin, Self::Env>;
        fn cancel_proposed_result(
            &mut self,
            match_id: u64,
        ) -> sails_rs::client::PendingCall<io::CancelProposedResult, Self::Env>;
        /// Step 1 of 2-step admin transfer: proposes a new admin address.
        /// The proposed address must call accept_admin() to complete the transfer.
        fn change_admin(
            &mut self,
            new_admin: ActorId,
        ) -> sails_rs::client::PendingCall<io::ChangeAdmin, Self::Env>;
        fn claim_final_prize(
            &mut self,
        ) -> sails_rs::client::PendingCall<io::ClaimFinalPrize, Self::Env>;
        fn claim_match_reward(
            &mut self,
            match_id: u64,
        ) -> sails_rs::client::PendingCall<io::ClaimMatchReward, Self::Env>;
        fn finalize_final_prize_pool(
            &mut self,
        ) -> sails_rs::client::PendingCall<io::FinalizeFinalPrizePool, Self::Env>;
        fn finalize_podium(
            &mut self,
            champion: String,
            runner_up: String,
            third_place: String,
        ) -> sails_rs::client::PendingCall<io::FinalizePodium, Self::Env>;
        fn finalize_result(
            &mut self,
            match_id: u64,
        ) -> sails_rs::client::PendingCall<io::FinalizeResult, Self::Env>;
        fn place_bet(
            &mut self,
            match_id: u64,
            predicted_score: Score,
            predicted_penalty_winner: Option<PenaltyWinner>,
        ) -> sails_rs::client::PendingCall<io::PlaceBet, Self::Env>;
        fn propose_from_oracle(
            &mut self,
            match_id: u64,
            oracle_program_id: ActorId,
        ) -> sails_rs::client::PendingCall<io::ProposeFromOracle, Self::Env>;
        fn propose_result(
            &mut self,
            match_id: u64,
            final_score: Score,
            penalty_winner: Option<PenaltyWinner>,
        ) -> sails_rs::client::PendingCall<io::ProposeResult, Self::Env>;
        fn register_match(
            &mut self,
            phase: String,
            home: String,
            away: String,
            kick_off: u64,
        ) -> sails_rs::client::PendingCall<io::RegisterMatch, Self::Env>;
        fn register_phase(
            &mut self,
            phase_name: String,
            start_time: u64,
            end_time: u64,
            points_weight: u32,
        ) -> sails_rs::client::PendingCall<io::RegisterPhase, Self::Env>;
        fn set_oracle_authorized(
            &mut self,
            oracle: ActorId,
            authorized: bool,
        ) -> sails_rs::client::PendingCall<io::SetOracleAuthorized, Self::Env>;
        fn submit_podium_pick(
            &mut self,
            champion: String,
            runner_up: String,
            third_place: String,
        ) -> sails_rs::client::PendingCall<io::SubmitPodiumPick, Self::Env>;
        fn sweep_match_dust_to_final_prize(
            &mut self,
            match_id: u64,
        ) -> sails_rs::client::PendingCall<io::SweepMatchDustToFinalPrize, Self::Env>;
        fn withdraw_final_prize_rounding_dust(
            &mut self,
        ) -> sails_rs::client::PendingCall<io::WithdrawFinalPrizeRoundingDust, Self::Env>;
        fn withdraw_protocol_fees(
            &mut self,
        ) -> sails_rs::client::PendingCall<io::WithdrawProtocolFees, Self::Env>;
        fn query_bets_by_user(
            &self,
            user: ActorId,
        ) -> sails_rs::client::PendingCall<io::QueryBetsByUser, Self::Env>;
        fn query_final_prize_claim_status(
            &self,
            wallet: ActorId,
        ) -> sails_rs::client::PendingCall<io::QueryFinalPrizeClaimStatus, Self::Env>;
        fn query_match(
            &self,
            match_id: u64,
        ) -> sails_rs::client::PendingCall<io::QueryMatch, Self::Env>;
        fn query_matches_by_phase(
            &self,
            phase: String,
        ) -> sails_rs::client::PendingCall<io::QueryMatchesByPhase, Self::Env>;
        fn query_state(&self) -> sails_rs::client::PendingCall<io::QueryState, Self::Env>;
        fn query_user_points(
            &self,
            user: ActorId,
        ) -> sails_rs::client::PendingCall<io::QueryUserPoints, Self::Env>;
        fn query_wallet_claim_status(
            &self,
            wallet: ActorId,
        ) -> sails_rs::client::PendingCall<io::QueryWalletClaimStatus, Self::Env>;
    }
    pub struct ServiceImpl;
    impl<E: sails_rs::client::GearEnv> Service for sails_rs::client::Service<ServiceImpl, E> {
        type Env = E;
        fn accept_admin(&mut self) -> sails_rs::client::PendingCall<io::AcceptAdmin, Self::Env> {
            self.pending_call(())
        }
        fn cancel_proposed_result(
            &mut self,
            match_id: u64,
        ) -> sails_rs::client::PendingCall<io::CancelProposedResult, Self::Env> {
            self.pending_call((match_id,))
        }
        fn change_admin(
            &mut self,
            new_admin: ActorId,
        ) -> sails_rs::client::PendingCall<io::ChangeAdmin, Self::Env> {
            self.pending_call((new_admin,))
        }
        fn claim_final_prize(
            &mut self,
        ) -> sails_rs::client::PendingCall<io::ClaimFinalPrize, Self::Env> {
            self.pending_call(())
        }
        fn claim_match_reward(
            &mut self,
            match_id: u64,
        ) -> sails_rs::client::PendingCall<io::ClaimMatchReward, Self::Env> {
            self.pending_call((match_id,))
        }
        fn finalize_final_prize_pool(
            &mut self,
        ) -> sails_rs::client::PendingCall<io::FinalizeFinalPrizePool, Self::Env> {
            self.pending_call(())
        }
        fn finalize_podium(
            &mut self,
            champion: String,
            runner_up: String,
            third_place: String,
        ) -> sails_rs::client::PendingCall<io::FinalizePodium, Self::Env> {
            self.pending_call((champion, runner_up, third_place))
        }
        fn finalize_result(
            &mut self,
            match_id: u64,
        ) -> sails_rs::client::PendingCall<io::FinalizeResult, Self::Env> {
            self.pending_call((match_id,))
        }
        fn place_bet(
            &mut self,
            match_id: u64,
            predicted_score: Score,
            predicted_penalty_winner: Option<PenaltyWinner>,
        ) -> sails_rs::client::PendingCall<io::PlaceBet, Self::Env> {
            self.pending_call((match_id, predicted_score, predicted_penalty_winner))
        }
        fn propose_from_oracle(
            &mut self,
            match_id: u64,
            oracle_program_id: ActorId,
        ) -> sails_rs::client::PendingCall<io::ProposeFromOracle, Self::Env> {
            self.pending_call((match_id, oracle_program_id))
        }
        fn propose_result(
            &mut self,
            match_id: u64,
            final_score: Score,
            penalty_winner: Option<PenaltyWinner>,
        ) -> sails_rs::client::PendingCall<io::ProposeResult, Self::Env> {
            self.pending_call((match_id, final_score, penalty_winner))
        }
        fn register_match(
            &mut self,
            phase: String,
            home: String,
            away: String,
            kick_off: u64,
        ) -> sails_rs::client::PendingCall<io::RegisterMatch, Self::Env> {
            self.pending_call((phase, home, away, kick_off))
        }
        fn register_phase(
            &mut self,
            phase_name: String,
            start_time: u64,
            end_time: u64,
            points_weight: u32,
        ) -> sails_rs::client::PendingCall<io::RegisterPhase, Self::Env> {
            self.pending_call((phase_name, start_time, end_time, points_weight))
        }
        fn set_oracle_authorized(
            &mut self,
            oracle: ActorId,
            authorized: bool,
        ) -> sails_rs::client::PendingCall<io::SetOracleAuthorized, Self::Env> {
            self.pending_call((oracle, authorized))
        }
        fn submit_podium_pick(
            &mut self,
            champion: String,
            runner_up: String,
            third_place: String,
        ) -> sails_rs::client::PendingCall<io::SubmitPodiumPick, Self::Env> {
            self.pending_call((champion, runner_up, third_place))
        }
        fn sweep_match_dust_to_final_prize(
            &mut self,
            match_id: u64,
        ) -> sails_rs::client::PendingCall<io::SweepMatchDustToFinalPrize, Self::Env> {
            self.pending_call((match_id,))
        }
        fn withdraw_final_prize_rounding_dust(
            &mut self,
        ) -> sails_rs::client::PendingCall<io::WithdrawFinalPrizeRoundingDust, Self::Env> {
            self.pending_call(())
        }
        fn withdraw_protocol_fees(
            &mut self,
        ) -> sails_rs::client::PendingCall<io::WithdrawProtocolFees, Self::Env> {
            self.pending_call(())
        }
        fn query_bets_by_user(
            &self,
            user: ActorId,
        ) -> sails_rs::client::PendingCall<io::QueryBetsByUser, Self::Env> {
            self.pending_call((user,))
        }
        fn query_final_prize_claim_status(
            &self,
            wallet: ActorId,
        ) -> sails_rs::client::PendingCall<io::QueryFinalPrizeClaimStatus, Self::Env> {
            self.pending_call((wallet,))
        }
        fn query_match(
            &self,
            match_id: u64,
        ) -> sails_rs::client::PendingCall<io::QueryMatch, Self::Env> {
            self.pending_call((match_id,))
        }
        fn query_matches_by_phase(
            &self,
            phase: String,
        ) -> sails_rs::client::PendingCall<io::QueryMatchesByPhase, Self::Env> {
            self.pending_call((phase,))
        }
        fn query_state(&self) -> sails_rs::client::PendingCall<io::QueryState, Self::Env> {
            self.pending_call(())
        }
        fn query_user_points(
            &self,
            user: ActorId,
        ) -> sails_rs::client::PendingCall<io::QueryUserPoints, Self::Env> {
            self.pending_call((user,))
        }
        fn query_wallet_claim_status(
            &self,
            wallet: ActorId,
        ) -> sails_rs::client::PendingCall<io::QueryWalletClaimStatus, Self::Env> {
            self.pending_call((wallet,))
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(AcceptAdmin () -> ());
        sails_rs::io_struct_impl!(CancelProposedResult (match_id: u64) -> ());
        sails_rs::io_struct_impl!(ChangeAdmin (new_admin: ActorId) -> ());
        sails_rs::io_struct_impl!(ClaimFinalPrize () -> ());
        sails_rs::io_struct_impl!(ClaimMatchReward (match_id: u64) -> ());
        sails_rs::io_struct_impl!(FinalizeFinalPrizePool () -> ());
        sails_rs::io_struct_impl!(FinalizePodium (champion: String, runner_up: String, third_place: String) -> ());
        sails_rs::io_struct_impl!(FinalizeResult (match_id: u64) -> ());
        sails_rs::io_struct_impl!(PlaceBet (match_id: u64, predicted_score: super::Score, predicted_penalty_winner: Option<super::PenaltyWinner>) -> ());
        sails_rs::io_struct_impl!(ProposeFromOracle (match_id: u64, oracle_program_id: ActorId) -> ());
        sails_rs::io_struct_impl!(ProposeResult (match_id: u64, final_score: super::Score, penalty_winner: Option<super::PenaltyWinner>) -> ());
        sails_rs::io_struct_impl!(RegisterMatch (phase: String, home: String, away: String, kick_off: u64) -> ());
        sails_rs::io_struct_impl!(RegisterPhase (phase_name: String, start_time: u64, end_time: u64, points_weight: u32) -> ());
        sails_rs::io_struct_impl!(SetOracleAuthorized (oracle: ActorId, authorized: bool) -> ());
        sails_rs::io_struct_impl!(SubmitPodiumPick (champion: String, runner_up: String, third_place: String) -> ());
        sails_rs::io_struct_impl!(SweepMatchDustToFinalPrize (match_id: u64) -> ());
        sails_rs::io_struct_impl!(WithdrawFinalPrizeRoundingDust () -> ());
        sails_rs::io_struct_impl!(WithdrawProtocolFees () -> ());
        sails_rs::io_struct_impl!(QueryBetsByUser (user: ActorId) -> Vec<super::UserBetView>);
        sails_rs::io_struct_impl!(QueryFinalPrizeClaimStatus (wallet: ActorId) -> super::FinalPrizeClaimStatus);
        sails_rs::io_struct_impl!(QueryMatch (match_id: u64) -> Option<super::Match>);
        sails_rs::io_struct_impl!(QueryMatchesByPhase (phase: String) -> Vec<super::Match>);
        sails_rs::io_struct_impl!(QueryState () -> super::IoSmartCupState);
        sails_rs::io_struct_impl!(QueryUserPoints (user: ActorId) -> u32);
        sails_rs::io_struct_impl!(QueryWalletClaimStatus (wallet: ActorId) -> super::WalletClaimStatus);
    }

    #[cfg(not(target_arch = "wasm32"))]
    pub mod events {
        use super::*;
        #[derive(PartialEq, Debug, Encode, Decode)]
        #[codec(crate = sails_rs::scale_codec)]
        pub enum ServiceEvents {
            PhaseRegistered(String),
            MatchRegistered((u64, String, String, String, u64)),
            OracleAuthorized((ActorId, bool)),
            BetAccepted((ActorId, u64, Score, Option<PenaltyWinner>, u128)),
            ResultProposed((u64, Score, Option<PenaltyWinner>, ActorId, u64)),
            ResultFinalized((u64, Score, Option<PenaltyWinner>)),
            SettlementPrepared((u64, u128)),
            PointsAwarded((ActorId, u64, u32)),
            MatchRewardClaimed((u64, ActorId, u128)),
            MatchDustSwept((u64, u128)),
            PodiumPickSubmitted((ActorId, String, String, String)),
            PodiumFinalized((String, String, String)),
            PodiumBonusAwarded((ActorId, u32)),
            FinalPrizeSent((u128, ActorId)),
            ProtocolFeesWithdrawn((u128, ActorId)),
            AdminProposed((ActorId, ActorId)),
            AdminChanged((ActorId, ActorId)),
            FinalPrizePoolFinalized((u128, u128)),
            FinalPrizeClaimed((ActorId, u128)),
            FinalPrizeRoundingDustWithdrawn((u128, ActorId)),
            ResultProposalCancelled((u64, ActorId)),
        }
        impl sails_rs::client::Event for ServiceEvents {
            const EVENT_NAMES: &'static [Route] = &[
                "PhaseRegistered",
                "MatchRegistered",
                "OracleAuthorized",
                "BetAccepted",
                "ResultProposed",
                "ResultFinalized",
                "SettlementPrepared",
                "PointsAwarded",
                "MatchRewardClaimed",
                "MatchDustSwept",
                "PodiumPickSubmitted",
                "PodiumFinalized",
                "PodiumBonusAwarded",
                "FinalPrizeSent",
                "ProtocolFeesWithdrawn",
                "AdminProposed",
                "AdminChanged",
                "FinalPrizePoolFinalized",
                "FinalPrizeClaimed",
                "FinalPrizeRoundingDustWithdrawn",
                "ResultProposalCancelled",
            ];
        }
        impl sails_rs::client::ServiceWithEvents for ServiceImpl {
            type Event = ServiceEvents;
        }
    }
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct Score {
    pub home: u8,
    pub away: u8,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum PenaltyWinner {
    Home,
    Away,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct UserBetView {
    pub match_id: u64,
    pub score: Score,
    pub penalty_winner: Option<PenaltyWinner>,
    pub stake_in_match_pool: u128,
    pub claimed: bool,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct FinalPrizeClaimStatus {
    pub wallet: ActorId,
    pub final_prize_finalized: bool,
    pub eligible: bool,
    pub amount_claimable: u128,
    pub already_claimed: bool,
    pub points: u32,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct Match {
    pub match_id: u64,
    pub phase: String,
    pub home: String,
    pub away: String,
    pub kick_off: u64,
    pub result: ResultStatus,
    pub match_prize_pool: u128,
    pub has_bets: bool,
    pub participants: Vec<ActorId>,
    pub total_winner_stake: u128,
    pub total_claimed: u128,
    pub settlement_prepared: bool,
    pub dust_swept: bool,
    pub finalized_at: Option<u64>,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum ResultStatus {
    Unresolved,
    Proposed {
        score: Score,
        penalty_winner: Option<PenaltyWinner>,
        oracle: ActorId,
        proposed_at: u64,
    },
    Finalized {
        score: Score,
        penalty_winner: Option<PenaltyWinner>,
    },
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct IoSmartCupState {
    pub admin: ActorId,
    pub protocol_fee_accumulated: u128,
    pub final_prize_accumulated: u128,
    pub matches: Vec<Match>,
    pub phases: Vec<PhaseConfig>,
    pub user_points: Vec<(ActorId, u32)>,
    pub podium_finalized: bool,
    pub r32_lock_time: Option<u64>,
    pub final_prize_finalized: bool,
    pub final_prize_claimable_total: u128,
    pub final_prize_rounding_dust: u128,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct PhaseConfig {
    pub name: String,
    pub start_time: u64,
    pub end_time: u64,
    pub points_weight: u32,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct WalletClaimStatus {
    pub wallet: ActorId,
    pub amount_claimable: u128,
    pub already_claimed: bool,
}
