const TEAM_FLAGS: Record<string, string> = {
  ARGENTINA: '/flags/argentina.jpg',
  BELGIUM: '/flags/belgium.jpg',
  BRAZIL: '/flags/brazil.jpg',
  CAMEROON: '/flags/cameroon.jpg',
  CANADA: '/flags/canada.png',
  CROATIA: '/flags/croatia.jpg',
  DENMARK: '/flags/denmark.jpg',
  ECUADOR: '/flags/ecuador.jpg',
  ENGLAND: '/flags/england.jpg',
  FRANCE: '/flags/france.jpg',
  GERMANY: '/flags/germany.jpg',
  GHANA: '/flags/ghana.jpg',
  IRAN: '/flags/iran.jpg',
  JAPAN: '/flags/japan.jpg',
  KOREA: '/flags/korea.jpg',
  MEXICO: '/flags/mexico.jpg',
  MOROCCO: '/flags/morocco.jpg',
  NETHERLANDS: '/flags/netherlands.jpg',
  POLAND: '/flags/poland.jpg',
  PORTUGAL: '/flags/portugal.jpg',
  QATAR: '/flags/qatar.jpg',
  'SAUDI ARABIA': '/flags/saudi_arabia.jpg',
  SENEGAL: '/flags/senegal.jpg',
  SERBIA: '/flags/serbia.jpg',
  'SOUTH AFRICA': '/flags/south_africa.png',
};


export { TEAM_FLAGS};